FROM mongo:4.4


RUN apt-get update
RUN apt-get install -y python3 python3-pip cron
RUN pip3 install --upgrade pip

RUN pip3 install requests
RUN pip3 install psutil
RUN pip3 install pymongo~=3.11.4

COPY ./system_health/ /system_health/

COPY ./system_health/crontabs/crontab.mongodb /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab
RUN touch /var/log/cron_mongodb.log


CMD cron && docker-entrypoint.sh mongod